services:
  gluetun:
    image: qmcgaw/gluetun
    container_name: gluetun
    cap_add:
      - NET_ADMIN
    restart: unless-stopped
    ports:
      - "8085:8080"
      - "6881:6881"
      - "6881:6881/udp"
    volumes:
      - ../../data/torrents/config:/gluetun
    environment:
      - VPN_SERVICE_PROVIDER=nordvpn
      - VPN_TYPE=openvpn
      - OPENVPN_USER=${OPENVPN_USER}
      - OPENVPN_PASSWORD=${OPENVPN_PASSWORD}
      - SERVER_COUNTRIES=United States
      - TZ=America/Denver
    networks:
      - westOS

  qbittorrent:
    image: ghcr.io/hotio/qbittorrent
    container_name: qbittorrent
    restart: unless-stopped
    network_mode: service:gluetun
    depends_on:
      - gluetun
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Denver
      - WEBUI_PORT=8080
    volumes:
      - ../../data/torrents/config:/config
      - ../../data/torrents/downloads:/downloads

networks:
  westOS:
    external: true
    name: westOS
