services:
  minecraft:
    image: itzg/minecraft-server:java17
    container_name: minecraft
    restart: unless-stopped
    ports:
      - "25565:25565"
    environment:
      EULA: "TRUE"
      TYPE: "FORGE"
      VERSION: "1.19.2"
      FORGE_VERSION: "43.2.6"
      MEMORY: "6G"
      USE_AIKAR_FLAGS: "true"
      SKIP_SERVER_PROPERTIES: "false"
      ENABLE_ROLLING_LOGS: "true"
    volumes:
      - ../../data/minecraft:/data
    networks:
      - westOS

networks:
  westOS:
    external: true
    name: westOS
