services:
  filebrowser:
    image: filebrowser/filebrowser:latest
    container_name: filebrowser
    restart: unless-stopped
    user: "1000:1000"
    volumes:
      - /mnt/media:/srv
      - ../../data/filebrowser/database/filebrowser.db:/database.db
      - ../../data/filebrowser/config:/config
    command: >
      --database /database.db
      --config /config/settings.json
      --root /srv
    expose:
      - "80"
    networks:
      - westOS

networks:
  westOS:
    external: true
    name: westOS
